# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

              #Create a docker image and push it to the hub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
         context: .
         file: ./Dockerfile
         push: true
         tags: ${{ secrets.DOCKERHUB_USERNAME }}/sms:latest


      - name: SFTP Sync
        # You may pin to the exact commit or the version.
        # uses: swillner/sftp-sync-action@629e1fe7a2db87d0f1da0e15a970b514fe398c09
        uses: swillner/sftp-sync-action@v1.0
        with:
          # server
          server: ec2-13-49-229-231.eu-north-1.compute.amazonaws.com
          # user
          user: ec2-user
          # Private SSH key for user (include via secrets if possible)
          user_private_key: ${{ secrets.FTP_PWD }} 
          # Public SSH key of host
          #host_public_key: # default is 
          # Local path to sync (default: .)
          local: ./target/SWE304-0.0.1-SNAPSHOT.jar
                


