# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_PWD }}

      - name: Image Build and Push
        uses: docker/build-push-action@v5
        with:
         context: .
         file: ./Dockerfile
         push: true
         tags: ${{ secrets.DOCKERHUB_USERNAME }}/sms:latest

#      - name: Create file for JAR file
#        run: mkdir jarfile
#
#      - name: Copy JAR file
#        run: cp ./target/SWE304-0.0.1-SNAPSHOT.jar jarfile

      - name: File Deploy
        # You may pin to the exact commit or the version.
        # uses: buxianshan/fine-sftp-deployer@57d6f88cf28663ccead95df84dc5ce752e2c8327
        uses: buxianshan/fine-sftp-deployer@v0.1.5
        with:
          username: ${{ secrets.FTP_USER }}
          server: ${{ secrets.FTP_SERVER }}
          ssh_private_key: ${{ secrets.FTP_PWD }}
          local_path: ./jarfile
          remote_path: /home/ec2-user
          clear_remote_path: false

      - name: File Deploy
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PWD }}
          port: 22
          source: "./target/SWE304-0.0.1-SNAPSHOT.jar"
          target: /home/ec2-user
          strip_components: 2